---
resource_types:
  - name: pull-request
    type: registry-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: resource-example
    type: git
    source:
      uri: https://github.com/ak1ra24/example-concourse.git
      branch: master
      # private_key: ((GITHUB_PRIVATE_KEY))
  - name: pr
    type: pull-request
    # check_every: 24h
    # webhook_token: ((webhook-token))
    source:
      repository: ak1ra24/example-concourse
      access_token: ((GITHUB_TOKEN))

jobs:
  - name: job-pr-test
    plan:
      - get: pr
        trigger: true
      - put: pr
        params:
          path: pr
          status: pending
      - task:
        file: pr/ci/job-pr-test.yml
        on_success:
          put: pr
          params:
            path: pr
            status: success
        on_failure:
          put: pr
          params:
            path: pr
            status: failure
  - name: job-push-master
    plan:
      - get: resource-2019-final-cloud
        trigger: true
      - task:
        file: pr/ci/job-push-master.yml
